#AGENDA DE CONTATOS: CRIE UM SISTEMA SIMPLES DE AGENDA QUE USE UM DICIONÁRIO. USE UM LOOP WHILE PARA MOSTRAR UM MENU COM  OPÇÕES DE ADICIONAR CONTATO, BUSCAR, SAIR:

contatos = {}

while True:
    opcao = input("Digite: 1(Adicionar Contato), 2(Buscar), 3(Sair) ")

    if opcao == "1":
        nome = input("Digite o nome do contato: ").lower()
        numero = input("Digite o número do contato:")
        contatos[nome] = numero
    elif opcao == "2":
        nome = input("Digite o nome do contato: ").lower()
        contato = contatos.get(nome, "Contato não encontrado!")
        print(contato)
    elif opcao == "3":
        print("Encerrando Programa!")
        break
    elif opcao == "4":
        print(contatos)
    else:
        print("Opção inválida")